name: Run Image Comparison Tests and Deploy HTML

on:
  workflow_dispatch: # Allow manual trigger from GitHub Actions

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run WebdriverIO Tests
        run: npm run test

      - name: Upload Test Images and HTML to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Branch where your HTML and images will be deployed
          folder: ./path_to_your_report_directory  # Update this to point to your HTML report folder
