name: Image Comparison Tests and Deploy

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Make wdio executable
        run: chmod +x ./node_modules/.bin/wdio

      - name: Run WebdriverIO Tests
        run: npm run test
        continue-on-error: true

      - name: Generate HTML Report
        run: |
          node ./reports/generateReport.js || echo "Failed to generate report"

      - name: Verify index.html existence
        run: ls -al ./reports

      - name: Ensure index.html is updated
        run: |
          mkdir -p gh-pages
          cp ./reports/gh-pages/index.html ./gh-pages/index.html
        shell: bash

      - name: Sanitize test suite name
        run: echo "sanitizedTestSuite=${{ github.event.inputs.testSuiteName }}" >> $GITHUB_ENV

      - name: Prepare files for deployment
        run: |
          mkdir -p gh-pages/images/baseline/desktop_chrome/${sanitizedTestSuite}
          mkdir -p gh-pages/images/actual/desktop_chrome/${sanitizedTestSuite}
          mkdir -p gh-pages/images/diff/desktop_chrome/${sanitizedTestSuite}
          cp -R ./baseLineImages/desktop_chrome/${sanitizedTestSuite}/* ./gh-pages/images/baseline/desktop_chrome/${sanitizedTestSuite}/
          cp -R ./actualImages/actual/desktop_chrome/${sanitizedTestSuite}/* ./gh-pages/images/actual/desktop_chrome/${sanitizedTestSuite}/
          cp -R ./actualImages/diff/desktop_chrome/${sanitizedTestSuite}/* ./gh-pages/images/diff/desktop_chrome/${sanitizedTestSuite}/

      - name: Verify image files are copied
        run: |
          ls -al ./gh-pages/images/baseline/desktop_chrome/${sanitizedTestSuite}
          ls -al ./gh-pages/images/actual/desktop_chrome/${sanitizedTestSuite}
          ls -al ./gh-pages/images/diff/desktop_chrome/${sanitizedTestSuite}

      - name: Upload reports folder for debugging
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./reports

      - name: Deploy to GitHub Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

